[build]
  publish = "."

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false

[[redirects]]
  from = "/admin"
  to = "/admin.html"
  status = 200
  force = true

[[redirects]]
  from = "/admin-panel"
  to = "/admin-panel.html"
  status = 200
  force = true

[[redirects]]
  from = "/supplier-register"
  to = "/supplier-register.html"
  status = 200
  force = true

[[redirects]]
  from = "/supplier-dashboard"
  to = "/supplier-dashboard.html"
  status = 200
  force = true
